# Generated by Django 5.0.2 on 2024-04-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='movie_image',
        ),
    ]
