# Generated by Django 5.0.2 on 2024-04-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_image',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='movies'),
        ),
    ]
